service: chargeflow-product

provider:
    name: aws
    runtime: nodejs12.x
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-east-1'}
    environment:
        STAGE: ${self:provider.stage}
        DB_CONNECTION: "mongodb+srv://admin:admin1234@chargeflow.culu1uo.mongodb.net/?retryWrites=true&w=majority"
    apiGateway:
        restApiId:
            "Fn::ImportValue": "chargeflow-${self:provider.stage}-apigw:ApiGwRestApiIdExport"
        restApiRootResourceId:
            "Fn::ImportValue": "chargeflow-${self:provider.stage}-apigw:ApiGwRootResourceIdExport"

functions:
    getProducts:
        handler: getProducts/getProducts.get
        timeout: 10
        events:
            - http:
                  path: products
                  method: get
                  cors: true
                  private: false
        layers:
            - ${self:custom.layer}
    getProduct:
        handler: getProduct/getProduct.get
        timeout: 10
        events:
            - http:
                  path: products/{id}
                  method: get
                  cors: true
                  private: false
        layers:
            - ${self:custom.layer}
    createOrder:
        handler: createOrder/createOrder.create
        timeout: 10
        events:
            - http:
                  path: orders
                  method: post
                  cors: true
                  private: false
        layers:
            - ${self:custom.layer}

package:
    excludeDevDependencies: false
    exclude:
        - serverless.yml
        - functions.yml
        - .vscode/**
        - .idea/**
        - test/**
        - package.json
        - package-lock.json
        - node_modules/**

plugins:
    - serverless-offline
    - serverless-pseudo-parameters
    - serverless-latest-layer-version

custom:
    layer: arn:aws:lambda:us-east-1:108705567938:layer:commons-${self:provider.stage}-layer:latest
