AWSTemplateFormatVersion: "2010-09-09"
Description: "Generate API Gateway infrastructure"
Parameters:
    ApiVersion:
        Description: "Project name for resource creation"
        Type: String
        Default: "v1"
    ProjectName:
        Description: "Project name for resource creation"
        Type: String
    Stage:
        Description: "Stage value of project"
        Type: String
        AllowedValues: ["dev", "uat", "prod"]
Resources:
    AppAPIGW:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Name: !Sub "${ProjectName}-${Stage}-apigw"
            ApiKeySourceType: "HEADER"
            EndpointConfiguration:
                Types:
                    - "EDGE"
Outputs:
    AppRestAPIId:
        Value: !Ref AppAPIGW
        Export:
            Name: !Sub "${AWS::StackName}:ApiGwRestApiIdExport"
    AppApiRootResourceId:
        Value: !GetAtt AppAPIGW.RootResourceId
        Export:
            Name: !Sub "${AWS::StackName}:ApiGwRootResourceIdExport"
